# Generated by Django 4.0.2 on 2022-03-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mpesa_number',
            field=models.CharField(default='07000', max_length=100),
            preserve_default=False,
        ),
    ]
