# Generated by Django 4.0.2 on 2022-03-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_mpesa_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=15, null=True),
        ),
    ]
